#---------BASIC CHORD---------#
FIND_SUCCESSOR = 1
FIND_PREDECESSOR = 2
GET_SUCCESSOR = 3
GET_PREDECESSOR = 4
NOTIFY = 5
CHECK_NODE = 6
CLOSEST_PRECEDING_FINGER = 7
STORE_KEY = 8
RETRIEVE_KEY = 9
JOIN = 11
NOTIFY_PRED = 12
FIRST_NOTIFY = 13
GET_COORDINATOR=14
#---------BASIC CHORD---------#



#---------SELF DISCOVERY---------#
DISCOVER = 15
ENTRY_POINT = 16
#---------SELF DISCOVERY---------#



#---------FTP---------#
AUTH_SSL = 'AUTH SSL'
AUTH_TLS = 'AUTH TLS'
AUTH = 'AUTH'
CWD = 'CWD'
DELE = 'DELE'
FEAT = 'FEAT'
LIST = 'LIST'
MKD = 'MKD'
PASV = 'PASV'
PORT = 'PORT'
PWD = 'PWD'
RETR = 'RETR'
RMD = 'RMD'
STOR = 'STOR'
TYPE_A = 'TYPE A'
TYPE_I = 'TYPE I'
USER = 'USER'
SYST = 'SYST'
QUIT = 'QUIT'
#---------FTP---------#


#--------AUXILIAR--------#
STOR_FILEDATA = 'STOR_FILEDATA'
REMOVE_DIR = 'REMOVE_DIR'
DELE_FILEDATA = 'DELE_FILEDATA'
#--------AUXILIAR--------#



#---------REPLICATION---------#
REPLICATE_STOR = 17
REPLICATE_DELE = 18
REPLICATE_MKD = 19
REPLICATE_STORFILEDATA = 20
REPLICATE_REMOVE_DIR = 21
REPLICATE_DELEFILEDATA = 22
#---------REPLICATION---------#



#---------COORDINATOR---------#
RELEASE = "RELEASE"
REQUEST = "REQUEST"
GRANT = "GRANT"
OK = 'OK'
#---------COORDINATOR---------#



#---------SEARCH---------#
FIND_COORDINATOR = 'COORD'
FIND_OWNER = 'OWNER'
#---------SEARCH---------#
