#---------BASIC CHORD---------#
FIND_SUCCESSOR = 1
FIND_PREDECESSOR = 2
GET_SUCCESSOR = 3
GET_PREDECESSOR = 4
NOTIFY = 5
CHECK_NODE = 6
CLOSEST_PRECEDING_FINGER = 7
STORE_KEY = 8
RETRIEVE_KEY = 9
JOIN = 11
NOTIFY_PRED = 12
FIRST_NOTIFY = 13
GET_COORDINATOR=14
#---------BASIC CHORD---------#



#---------SELF DISCOVERY---------#
DISCOVER = 15
ENTRY_POINT = 16
#---------SELF DISCOVERY---------#



#---------FTP---------#
CWD = 'CWD'
DELE = 'DELE'
LIST = 'LIST'
MKD = 'MKD'
PASV = 'PASV'
PORT = 'PORT'
PWD = 'PWD'
RETR = 'RETR'
RMD = 'RMD'
STOR = 'STOR'
SYST = 'SYST'
QUIT = 'QUIT'
#---------FTP---------#


#--------AUXILIAR--------#
STOR_FILEDATA = 'STOR_FILEDATA'
REMOVE_DIR = 'REMOVE_DIR'
#--------AUXILIAR--------#



#---------REPLICATION---------#
REPLICATE_STOR = 17
REPLICATE_DELE = 18
REPLICATE_MKD = 19
REPLICATE_STORFILEDATA = 20
#---------REPLICATION---------#